const products = [
    {
        id: 1,
        name: "Product 1",
        price: 15.25,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo1.png',
    },
    {
        id: 2,
        name: "Product 2",
        price: 22.99,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo2.png',
    },
    {
        id: 3,
        name: "Product 3",
        price: 18.75,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo3.png',
    },
    {
        id: 4,
        name: "Product 4",
        price: 29.99,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo4.png',
    },
    {
        id: 5,
        name: "Product 5",
        price: 12.50,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo5.png',
    },
    {
        id: 6,
        name: "Product 6",
        price: 24.99,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo1.png',
    },
    {
        id: 7,
        name: "Product 7",
        price: 19.95,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo2.png',
    },
    {
        id: 8,
        name: "Product 8",
        price: 34.50,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo3.png',
    },
    {
        id: 9,
        name: "Product 9",
        price: 16.99,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo4.png',
    },
    {
        id: 10,
        name: "Product 10",
        price: 27.75,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo5.png',
    },
    {
        id: 11,
        name: "Product 11",
        price: 14.50,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo1.png',
    },
    {
        id: 12,
        name: "Product 12",
        price: 31.25,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo2.png',
    },
    {
        id: 13,
        name: "Product 13",
        price: 20.00,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo3.png',
    },
    {
        id: 14,
        name: "Product 14",
        price: 26.99,
        availability: "Out of Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo4.png',
    },
    {
        id: 15,
        name: "Product 15",
        price: 17.75,
        availability: "In Stock",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
        image: './src/img/photo5.png',
    },
];
  
export default products;